### ISSUE TITLE
Extra whitespace in CSS file selector

### ISSUE THREAD

**Issue by agung-wete** [gwarnants/FunctionList-PHP-Patch#2]
hi
With CSS file, there is extra whitespace in SELECTOR group, if css selector prepend with whitespace(tab/space)

**Comment by gwarnants** [comment]
Thanks for that issue, it's now fixed

**Comment by agung-wete** [comment]
Great, thank you. Small glitch, check below code:

```css
@CHARSET "UTF-8";
			/*demo page css*/


				.demoHeaders {
					margin-top: 2em;
				}
				#dialog_link {
					padding: .4em 1em .4em 20px;
					text-decoration: none;
					position: relative;
				}
```
Class demoHeaders is missing in SELECTOR list, because of this "/*demo page css*/".
If we removed it or we place it above "@CHARSET "UTF-8";" the class demoHeaders  appears in list
